---
title: 'Supporting Information: Contact angle statistics'
author: "Clifton Anderson"
date: "July 2, 2018"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(xlsx)
library(car)
```

## Plots and ANOVA results

A model was fitted to consider the effects of (1) Drop location, (2) Liquid, and (3) the plasma treatment.

```{r Data importing and manipulating}

raw <- read.xlsx2('C:/Users/cdhig/Documents/MS-Thesis-Pitt/Data-analysis/contact angles.xlsx',sheetIndex=1,colClasses = NA)
printed <- raw[raw$Finish!='PP',]
ggplot(printed,aes(x=Location,y=avg))+geom_point()+facet_grid(Liquid ~ Treatment)

# Duplicate treatment for more descriptive factor name
raw$CoatingType <- raw$Treatment 

# Collapse the factor levels into the type of treatment
levels(raw$CoatingType) <- list(plasma=c('blown3min.1', 'blown3min.2',
                                         'quick.dry', 'plas_coated'),
                                clean= c('as is', 'clean', 'etoh_ace', 'washed',
                                         'wiped', 'wiped_etoh_ace', 'wiped_water'),
                                paa=   c('paa'),
                                support=c('support'))

# Remove unwanted factor levels
TreatmentSum <- filter(raw,!Treatment %in% c('as is',  'paa', 'support', 'washed', 'wiped_water') &
                         !Finish %in% c('glass','matte') &
                          Time=='SS') %>%
  select(.,Finish,Liquid,CoatingType,Treatment,avg) %>%
  droplevels()

# summarize group means 
CAtable <- TreatmentSum %>% group_by(Finish,Liquid,CoatingType) %>%
  summarise(n=n(),
            Contact.Angle=mean(avg),
            SD = sd(avg),
            'Cos(theta)'=cos(3.14159/180*Contact.Angle)) #%>%
  # knitr::kable(.,
               # caption='contact angle of water and plasma on clean and plasma coated surfaces',
               # digits=c(0,0,0,0,1,1,3))


CAtable
# convert CA table to html for easy pasting into word.
# htmlTable(txtRound(CAtable[,1:ncol(CAtable)],digits=c(0,0,1,0,1,1,3)))

```

```{r ANOVA stuff}
drops <- raw
drops$Location <- factor(drops$Location)
drop.aov <- lm(avg ~ Location*Liquid*Treatment, data=drops)

summary(drop.aov)
```

None of the effects including 'Location' are significant, suggesting surface treatments were sufficiently homogeneous.


```{r drop.aov assumptions}
leveneTest(avg ~ Location*Liquid*Treatment,data=drops)
plot(drop.aov,2)
```  

## Plasma coating t-tests
hi
```{r plasma coating t-tests}
SS <- subset(raw,Time=='SS' & Finish=='glossy' & Treatment != 'paa')
SS %>% 
  filter(.,Treatment!='clean'& Treatment != 'wiped',Liquid=='plasma') %>%
  pairwise.t.test(.$avg,.$Treatment,data=.,pool.sd=FALSE,p.adj='bonf')
```

```{r PP coating tests}
PP <- raw[raw$Finish=='PP',]
PP %>% group_by(Treatment,Liquid) %>% summarise(n=n(),Angle=mean(avg),SD=sd(avg),Conf95=SD/sqrt(n)*qt(0.95,df=n-1),'Cos'=cos(Angle*3.14159/180))
ggplot(PP,aes(Treatment,avg,color=Liquid)) + geom_jitter(width=0.25)

```

```{r coating on printed vs glossy}
coatings <- subset(raw,Treatment %in% c('blown3min.1','blown3min.2','plas_coated','quick.dry'))

ggplot(coatings,aes(Treatment,avg,color=Liquid))+geom_point() + facet_wrap(~Finish)
```

```{r wetting thoughts}
SS %>% group_by(Treatment,Liquid) %>% summarise(n=n(),Angle=mean(avg),SD=sd(avg),Conf95=SD/sqrt(n)*qt(0.95,df=n-1),'Cos'=cos(Angle*3.14159/180))
```
